export type PublicConfig = {
  companyName: string;
  systemName: string;
  companyLogoUrl?: string | null;
  selfCorrectionMaxDays?: number;
  colorApproved: string;
  colorRejected: string;
  colorManualCorrection: string;
  colorBulkEntry: string;
  colorBreakCredit: string;
  colorSickLeave: string;
  colorHolidayOrWeekend: string;
  colorHolidayOrWeekendWork: string;
  colorVacationWarning: string;
  colorWebEntry: string;
  colorOvertime: string;
  colorNavMainActive: string;
  colorNavMainInactive: string;
  colorNavSubActive: string;
  colorNavSubInactive: string;
  colorNavTextActive: string;
  colorNavTextInactive: string;
  colorNavSubTextActive: string;
  colorNavSubTextInactive: string;
  colorApprovedEnabled?: boolean;
  colorRejectedEnabled?: boolean;
  colorManualCorrectionEnabled?: boolean;
  colorBulkEntryEnabled?: boolean;
  colorBreakCreditEnabled?: boolean;
  colorSickLeaveEnabled?: boolean;
  colorHolidayOrWeekendEnabled?: boolean;
  colorHolidayOrWeekendWorkEnabled?: boolean;
  colorVacationWarningEnabled?: boolean;
  colorWebEntryEnabled?: boolean;
  colorOvertimeEnabled?: boolean;
  colorNavMainActiveEnabled?: boolean;
  colorNavMainInactiveEnabled?: boolean;
  colorNavSubActiveEnabled?: boolean;
  colorNavSubInactiveEnabled?: boolean;
  colorNavTextActiveEnabled?: boolean;
  colorNavTextInactiveEnabled?: boolean;
  colorNavSubTextActiveEnabled?: boolean;
  colorNavSubTextInactiveEnabled?: boolean;
};

export function applyTheme(config: PublicConfig): void {
  const root = document.documentElement;
  const bgColor = (enabled: boolean | undefined, color: string) => (enabled ?? true ? color : "#ffffff");
  const textColor = (enabled: boolean | undefined, color: string, fallback = "#111827") => (enabled ?? true ? color : fallback);
  root.style.setProperty("--approved", bgColor(config.colorApprovedEnabled, config.colorApproved));
  root.style.setProperty("--rejected", bgColor(config.colorRejectedEnabled, config.colorRejected));
  root.style.setProperty("--manual", bgColor(config.colorManualCorrectionEnabled, config.colorManualCorrection));
  root.style.setProperty("--bulk-entry", bgColor(config.colorBulkEntryEnabled, config.colorBulkEntry));
  root.style.setProperty("--break-credit", bgColor(config.colorBreakCreditEnabled, config.colorBreakCredit));
  root.style.setProperty("--sick", bgColor(config.colorSickLeaveEnabled, config.colorSickLeave));
  root.style.setProperty("--holiday-day", bgColor(config.colorHolidayOrWeekendEnabled, config.colorHolidayOrWeekend));
  root.style.setProperty("--holiday", bgColor(config.colorHolidayOrWeekendWorkEnabled, config.colorHolidayOrWeekendWork));
  root.style.setProperty("--warning", bgColor(config.colorVacationWarningEnabled, config.colorVacationWarning));
  root.style.setProperty("--web-entry", bgColor(config.colorWebEntryEnabled, config.colorWebEntry));
  root.style.setProperty("--overtime", textColor(config.colorOvertimeEnabled, config.colorOvertime));
  root.style.setProperty("--nav-main-active-bg", bgColor(config.colorNavMainActiveEnabled, config.colorNavMainActive));
  root.style.setProperty("--nav-main-inactive-bg", bgColor(config.colorNavMainInactiveEnabled, config.colorNavMainInactive));
  root.style.setProperty("--nav-sub-active-bg", bgColor(config.colorNavSubActiveEnabled, config.colorNavSubActive));
  root.style.setProperty("--nav-sub-inactive-bg", bgColor(config.colorNavSubInactiveEnabled, config.colorNavSubInactive));
  root.style.setProperty("--nav-text-active", textColor(config.colorNavTextActiveEnabled, config.colorNavTextActive, "#ffffff"));
  root.style.setProperty("--nav-text-inactive", textColor(config.colorNavTextInactiveEnabled, config.colorNavTextInactive, "#ffffff"));
  root.style.setProperty("--nav-sub-text-active", textColor(config.colorNavSubTextActiveEnabled, config.colorNavSubTextActive, "#111827"));
  root.style.setProperty("--nav-sub-text-inactive", textColor(config.colorNavSubTextInactiveEnabled, config.colorNavSubTextInactive, "#111827"));
}
